//! Build script for vanadium-riscv-arch-tests.
//!
//! # What this does
//!
//! 1. Expects `vendor/riscv-arch-test` to already be present.  If it is not,
//!    an empty test file is generated and the build silently succeeds.  See
//!    `README.md` for instructions on how to populate that directory.
//! 2. Expects golden reference outputs in `references/{ext}/{stem}.reference_output`
//!    (relative to this crate).  See `README.md` for how to generate them with
//!    Spike.  Tests whose reference output is missing are skipped.
//! 3. Locates a RISC-V cross-compiler (`riscv32-unknown-elf-gcc` or
//!    `riscv64-unknown-elf-gcc`).  If none is found, an empty test file is
//!    generated and the build silently succeeds.
//! 4. Compiles each `.S` test source to an ELF binary in `$OUT_DIR/elf/`.
//! 5. Copies the matching golden reference output into `$OUT_DIR/references/`.
//! 6. Generates `$OUT_DIR/arch_tests.rs`, which is `include!`-d by
//!    `tests/arch_tests.rs` and expands to one `#[test]` function per test.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// ISA extensions to test.  Each tuple is (extension name, -march value).
/// We use a single superset march for all tests; the individual test .S
/// files control which instructions they actually emit.
const EXTENSIONS: &[(&str, &str)] = &[
    ("I", "rv32imac_zicsr"),
    ("M", "rv32imac_zicsr"),
    ("A", "rv32imac_zicsr"),
    ("C", "rv32imac_zicsr"),
];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Re-run when model files, build script, or reference outputs change.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=model/model_test.h");
    println!("cargo:rerun-if-changed=model/link.ld");
    println!("cargo:rerun-if-changed=references");

    let vendor_dir = manifest_dir.join("vendor");
    let repo_dir = vendor_dir.join("riscv-arch-test");
    let suite_dir = repo_dir.join("riscv-test-suite");

    // ── Step 1: verify the vendor repo is present ──────────────────────────
    if !suite_dir.exists() {
        println!("cargo:warning=vendor/riscv-arch-test not found; no arch tests generated.");
        println!("cargo:warning=See riscv-arch-tests/README.md for setup instructions.");
        write_empty_tests(&out_dir);
        return;
    }

    // Let Cargo track top-level arch_test.h so changes trigger a rebuild.
    println!(
        "cargo:rerun-if-changed={}",
        suite_dir.join("env/arch_test.h").display()
    );

    // ── Step 2: locate cross-compiler ───────────────────────────────────────
    let gcc = match find_riscv_gcc() {
        Some(g) => g,
        None => {
            println!(
                "cargo:warning=No riscv32/64-unknown-elf-gcc found on PATH; \
                 no arch tests generated."
            );
            write_empty_tests(&out_dir);
            return;
        }
    };

    // ── Step 3–5: compile & generate ────────────────────────────────────────
    let env_dir = suite_dir.join("env");
    let model_dir = manifest_dir.join("model");
    let elf_root = out_dir.join("elf");
    let ref_root = out_dir.join("references");

    let mut generated = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Each function loads a compiled arch-test ELF, runs it through the\n\
         // Vanadium CPU, and compares its signature against the golden reference.\n\n",
    );

    for (ext, march) in EXTENSIONS {
        let src_dir = suite_dir.join(format!("rv32i_m/{ext}/src"));
        let ref_dir = manifest_dir.join("references").join(ext);
        let elf_dir = elf_root.join(ext);
        let out_ref_dir = ref_root.join(ext);

        if !src_dir.exists() {
            println!(
                "cargo:warning=Test source directory {src_dir:?} not found; \
                 skipping extension {ext}."
            );
            continue;
        }

        fs::create_dir_all(&elf_dir).expect("failed to create elf output dir");
        fs::create_dir_all(&out_ref_dir).expect("failed to create reference output dir");

        // Track test source files so Cargo can detect additions/removals.
        println!("cargo:rerun-if-changed={}", src_dir.display());

        let mut entries: Vec<_> = fs::read_dir(&src_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in entries {
            let src_path = entry.path();
            if src_path.extension().and_then(|x| x.to_str()) != Some("S") {
                continue;
            }
            let stem = src_path.file_stem().unwrap().to_str().unwrap().to_owned();

            // Skip tests that declare an ISA extension Vanadium doesn't support
            // (e.g. Zcb).  Reading the first ~2 KB is enough to find RVTEST_ISA.
            let src_head = fs::read_to_string(&src_path).unwrap_or_default();
            if src_head.contains("_Zcb") || src_head.contains("_zcb") {
                continue;
            }

            // Skip test for the CEBREAK instruction, which Vanadium doesn't support
            if src_head.contains("cebreak") {
                continue;
            }

            // Locate reference output (local references/ directory, not the upstream repo).
            let ref_src = ref_dir.join(format!("{stem}.reference_output"));
            if !ref_src.exists() {
                println!(
                    "cargo:warning=No reference output for {ext}/{stem}; \
                     skipping. Run Spike to generate it \
                     (see riscv-arch-tests/README.md)."
                );
                continue;
            }

            let elf_out = elf_dir.join(format!("{stem}.elf"));
            let ref_out = out_ref_dir.join(format!("{stem}.reference_output"));

            // Copy reference output into OUT_DIR.
            fs::copy(&ref_src, &ref_out)
                .unwrap_or_else(|_| panic!("failed to copy reference for {ext}/{stem}"));

            // Compile .S → ELF.
            let ok = Command::new(&gcc)
                .args([
                    &format!("-march={march}"),
                    "-mabi=ilp32",
                    "-static",
                    "-mcmodel=medany",
                    "-fvisibility=hidden",
                    "-nostdlib",
                    "-nostartfiles",
                    "-I",
                    env_dir.to_str().unwrap(),
                    "-I",
                    model_dir.to_str().unwrap(),
                    "-T",
                    model_dir.join("link.ld").to_str().unwrap(),
                    "-DXLEN=32",
                    "-DTEST_CASE_1=1",
                    src_path.to_str().unwrap(),
                    "-o",
                    elf_out.to_str().unwrap(),
                ])
                .status()
                .map(|s| s.success())
                .unwrap_or(false);

            if !ok {
                println!("cargo:warning=Compilation failed for {ext}/{stem}; skipping.");
                // Remove stale ELF so a stale include_bytes! isn't generated.
                let _ = fs::remove_file(&elf_out);
                continue;
            }

            // Generate #[test] function.
            let fn_name = make_test_name(ext, &stem);
            let elf_path = elf_out.to_string_lossy().into_owned();
            let ref_path = ref_out.to_string_lossy().into_owned();

            generated.push_str(&format!(
                "#[test]\nfn {fn_name}() {{\n    \
                 vanadium_riscv_arch_tests::run_test(\n        \
                 include_bytes!(\"{elf_path}\"),\n        \
                 include_str!(\"{ref_path}\"),\n    ).unwrap();\n}}\n\n"
            ));
        }
    }

    let out_file = out_dir.join("arch_tests.rs");
    fs::write(&out_file, generated).expect("failed to write arch_tests.rs");
}

/// Converts e.g. ("I", "add-01") → "i_add_01".
fn make_test_name(ext: &str, stem: &str) -> String {
    let sanitised: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("{}_{sanitised}", ext.to_ascii_lowercase())
}

/// Looks for a RISC-V cross-compiler on `PATH`.
fn find_riscv_gcc() -> Option<String> {
    for candidate in [
        "riscv32-unknown-elf-gcc",
        "riscv64-unknown-elf-gcc",
        "riscv32-linux-gnu-gcc",
        "riscv64-linux-gnu-gcc",
    ] {
        if Command::new(candidate).arg("--version").output().is_ok() {
            return Some(candidate.to_string());
        }
    }
    None
}

/// Writes an empty (comment-only) arch_tests.rs when no tests can be generated.
fn write_empty_tests(out_dir: &Path) {
    let path = out_dir.join("arch_tests.rs");
    fs::write(
        path,
        "// No RISC-V arch tests were generated.\n\
         // See riscv-arch-tests/README.md for setup instructions.\n",
    )
    .expect("failed to write empty arch_tests.rs");
}
