[package]
name = "app-vanadium"
version = "0.0.1"
authors = ["Salvatore Ingala"]
edition = "2021"

[dependencies]
common = { path = "../common", features=["device_sdk"] }
include_gif = "1.2.0"
serde = {version="1.0.192", default-features = false, features = ["derive"]}
serde-json-core = { git = "https://github.com/rust-embedded-community/serde-json-core"}
hex = { version = "0.4.3", default-features = false, features = ["serde", "alloc"] }
numtoa = "0.2.4"
postcard = { version = "1.0.8", features = ["alloc"] }
ledger_secure_sdk_sys = "1.6.1"
zeroize = "1.8.1"
ledger_device_sdk = "1.19.1"

[profile.release]
opt-level = 3
lto = true

[features]
default = []
pending_review_screen = []

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = ["44'/1'"]
name = "Vanadium"

[package.metadata.ledger.nanox]
icon = "vanadium_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "vanadium_14x14.gif"

[package.metadata.ledger.stax]
icon = "vanadium_32x32.gif"

[package.metadata.ledger.flex]
icon = "vanadium_40x40.gif"

[workspace]
