[package]
name = "vndbench-sha256"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { package = "vanadium-app-sdk", path = "../../../app-sdk"}
sha2 = { version = "0.10.8", default-features = false }

[workspace]
