[package]
name = "vanadium_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1"
proc-macro2 = "1"
proc-macro-error2 = { version = "2.0", default-features = false }

[features]
default = []
wrapped_serializable = []
